baseurl = "http://rizahmed.github.io/"
title = "Rizwan Ahmed"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "rizahmed"

[markup.highlight]
style = "github-dark"

[params]
  author = "Rizwan Ahmed"
  info = "Backend developer"
  description = "Hello, I'm Rizwan Ahmed"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpeg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/rizahmeds/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/riz_ahmeds/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/rizahmeds/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-instagram fa-2x"
  weight = 4
  url = "https://www.instagram.com/riz_ahmeds/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
